/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALEJA
 */
public class TraducciondeNumALetras extends javax.swing.JFrame {

    /**
     * Creates new form TraducciondeNumALetras
     */
    public TraducciondeNumALetras() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        btntraducir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtprocedimiento = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Traducción de números a letras");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 33, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Por favor introduce el número que deseas traducir: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 66, -1, -1));
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, 37));

        btntraducir.setText("Traducir");
        btntraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntraducirActionPerformed(evt);
            }
        });
        getContentPane().add(btntraducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 142, -1, -1));

        txtprocedimiento.setColumns(20);
        txtprocedimiento.setRows(5);
        jScrollPane1.setViewportView(txtprocedimiento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 171, 247, 107));

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 284, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 284, -1, -1));

        jButton3.setText("Ir a menú");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfdfgrfyiu/DosxN.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Lab7 a=new Lab7();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtvalor.setText("");
        txtprocedimiento.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btntraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntraducirActionPerformed
        // TODO add your handling code here:
        String valor=txtvalor.getText();
        int num=Integer.parseInt(valor);
        //Mostrar titulo
        String unidades[] = 
        {"cero", "uno", "dos" ,"tres" ,"cuatro" ,"cinco" ,
            "seis" ,"siete" ,"ocho" ,"nueve","diez"};
        String especiales[] = 
        {"once", "doce","trece","catorce", "quince", 
            "diezciseis", "diecisiete", "dieciocho", "diecinueve"};
        String decenas[] = 
        {"veinte", "treinta","cuarenta","cincuenta", "sesenta",
            "setenta", "ochenta", "noventa"};
        String centenas[]=
        {"cien", "doscientos","trecientos","cuatrocientos","quinientos","seiscientos",
        "setecientos", "ochocientos", "novecientos"}; 
        String unidadesmil[]=
        {"mil","dos mil","tres mil","cuatro mil","cinco mil","seis mil",
            "siete mil","ocho mil","nueve mil"};   
        
      txtprocedimiento.append("La traducción es:"); 
        if(num<11)
            txtprocedimiento.append("\n" +unidades[num]);
        else if (num<20)
            txtprocedimiento.append("\n" +especiales[num-11]);
        //Decenas (20,30,etc//
        else if (num<100){
            int unid = num % 10;
            int dec = num/10;
            if(unid == 0)
                txtprocedimiento.append("\n"+decenas[dec-2]);
            else 
                txtprocedimiento.append("\n"+decenas[dec-2]+ "y" +unidades[unid]);
        }
        //centenas (100,200,etc)//
        else if(num<1000){
            if(num<111){
                    if(num==100)
                    txtprocedimiento.append("\n" + centenas[0]);
                    else
                    if(num != 100)
                    txtprocedimiento.append("\n" + centenas[0]+"to ");
                    txtprocedimiento.append(unidades[num-100]);                
            }else
                if(num<120){
                    txtprocedimiento.append('\n' + centenas[0]+"to ");
                    txtprocedimiento.append(especiales[num-111]);
            }else
                if(num<1000){
                    int unid = num % 10;
                    int cent= num/100;
                    int dec = (num-(cent*100))/10;
                    if(unid == 0){
                        if(num<200){
                            txtprocedimiento.append('\n' + centenas[cent-1]+"to ");
                            txtprocedimiento.append( decenas[dec-2]);
                            }else
                        if(unid <= 200)
                        txtprocedimiento.append("\n" + centenas[cent-1]);
                        txtprocedimiento.append( " " +decenas[dec-2]);
                        }else
                    if(num<200){
                        txtprocedimiento.append("\n" + centenas[cent-1]+ "to ");
                        txtprocedimiento.append(decenas[dec-2] + " y " + unidades[unid]);
                        }else
                    if(unid <= 200)
                    txtprocedimiento.append("\n" + centenas[cent-1]);
                    txtprocedimiento.append(" " +decenas+ " y " + unidades[unid]);
                }
         }
        //Unidades de mil (mil,dos mil,etc)//
        else if (num<10000){
             int unid = num % 1000;
             int dec=num/10;
            int unmil = num/1000;
            if(unid == 0)
                txtprocedimiento.append("\n" + unidadesmil[unmil-1]);                
            else
                txtprocedimiento.append("\n" + unidadesmil[unmil-1]
                                       + "_" + unidades[unid]); 
            if(unid==10)
                txtprocedimiento.append("\n" +unidadesmil[unmil-1]); 
         }
        else
            txtprocedimiento.append("El número debe ser menor a 9000");
    }//GEN-LAST:event_btntraducirActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraducciondeNumALetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraducciondeNumALetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraducciondeNumALetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraducciondeNumALetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraducciondeNumALetras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntraducir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtprocedimiento;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
